from __future__ import annotations

from typing import Optional, Any


class Db:
    """
    NanoTS 数据库实例 (Community Edition).

    一个嵌入式、仅追加写入、高性能的时序数据库内核。
    """

    def __init__(
        self,
        path: str,
        retention_ms: Optional[int] = None,
        auto_maintenance: Optional[dict[str, Any] | bool] = None,
    ) -> None: ...

    def create_table(self, table: str, columns: list[str]) -> None: ...
    def create_table_typed(self, table: str, columns: list[tuple[str, str]]) -> None: ...
    def append(self, series: str, ts_ms: int, value: float) -> int: ...
    def append_row(self, table: str, ts_ms: int, values: list[float]) -> int: ...
    def append_row_typed(self, table: str, ts_ms: int, values: list[Any]) -> int: ...
    def flush(self) -> None: ...
    def pack_table(self, table: str, target_segment_points: int) -> None: ...

    def query_range(self, series: str, start_ms: int, end_ms: int) -> list[tuple[int, float]]: ...
    def query_table_range_columns(
        self, table: str, start_ms: int, end_ms: int
    ) -> tuple[list[int], list[list[float]]]: ...
    def query_table_range_typed(
        self, table: str, start_ms: int, end_ms: int
    ) -> tuple[list[int], list[list[Any]]]: ...

    # Returns (schema_capsule, array_capsule) for Arrow C Data Interface import.
    def query_table_range_arrow_capsules(
        self, table: str, start_ms: int, end_ms: int
    ) -> tuple[Any, Any]: ...

    # Append rows from Arrow C Data Interface capsules.
    def append_rows_arrow_capsules(
        self, table: str, schema_capsule: Any, array_capsule: Any
    ) -> int: ...

    # Returns a single Arrow C Stream capsule for SQL results.
    def query_sql_arrow_stream_capsule(self, sql: str) -> Any: ...

    def stats(self, table: str) -> dict[str, Any]: ...
    def diagnose(self) -> dict[str, Any]: ...
